name: Update badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "02 22 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@master
          ACCLAIM_USER: ana-caroline-sanchez-silva
